icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "battery"
interval = 60
format = " $icon $percentage $time "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
mappings = { "English (US)" = "US", "Lithuanian" = "LT" }

[[block]]
block = "sound"

[[block]]
block = "backlight"
format = " $icon $brightness "
step_width = 5

[[block]]
block = "time"
interval = 60 
format = "$icon $timestamp.datetime(f:'%Y-%m-%d %H:%M') "
[[block.click]]
button = "left"
cmd = "yad --calendar --undecorated --fixed --close-on-unfocus --no-buttons"

[[block]]
block = "custom"
command = "echo '  '" # Power icon (requires Font Awesome)
interval = "once"
[[block.click]]
button = "left"
cmd = "~/.config/scripts/powermenu.sh"

