[opener]
edit = [
    { run = 'vimx "$@"', block = true, desc = "Vim" },
    { run = 'nvim "$@"', block = true, desc = "Neovim" },
    { run = 'zed "$@"', block = true, desc = "Zed" }
]

[open]
rules = [
    { url = "*.ini", use = "edit" },
    { url = "*.sh", use = "edit" },
    { url = "*.vim", use = "edit" },
    { url = ".vimrc", use = "edit" },
    { mime = "text/*", use = "edit" }
]
