[opener]
edit = [
    { run = 'neovide --no-fork "$@"', block = true, desc = "Neovide" },
    { run = 'nvim "$@"', block = true, desc = "Neovim" },
    { run = 'zed "$@"', block = true, desc = "Zed" },
    { run = 'vim "$@"', block = true, desc = "Vim" }
]

[open]
prepend_rules = [
    { url = "*.ini", use = "edit" },
    { url = "*.sh", use = "edit" },
    { url = "*.vim", use = "edit" },
    { url = ".vimrc", use = "edit" },
    { mime = "text/*", use = "edit" }
]
